notebook usado para filtrar modelos de interesse e selecionar colunas SMART

In [2]:
import os
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
csv_files = [arquivo for arquivo in os.listdir('../data/data_q3_2024') if arquivo.startswith("2024-07") & arquivo.endswith(".csv")]
csv_files

['2024-07-01.csv',
 '2024-07-02.csv',
 '2024-07-03.csv',
 '2024-07-04.csv',
 '2024-07-05.csv',
 '2024-07-06.csv',
 '2024-07-07.csv',
 '2024-07-08.csv',
 '2024-07-09.csv',
 '2024-07-10.csv',
 '2024-07-11.csv',
 '2024-07-12.csv',
 '2024-07-13.csv',
 '2024-07-14.csv',
 '2024-07-15.csv',
 '2024-07-16.csv',
 '2024-07-17.csv',
 '2024-07-18.csv',
 '2024-07-19.csv',
 '2024-07-20.csv',
 '2024-07-21.csv',
 '2024-07-22.csv',
 '2024-07-23.csv',
 '2024-07-24.csv',
 '2024-07-25.csv',
 '2024-07-26.csv',
 '2024-07-27.csv',
 '2024-07-28.csv',
 '2024-07-29.csv',
 '2024-07-30.csv',
 '2024-07-31.csv']

In [4]:
n_columns = [1, 5, 7, 184, 187, 188, 189, 190, 193, 194, 197, 198, 240, 241, 242]
normalized_cols = [f'smart_{n}_normalized' for n in n_columns]
#raw_cols = [f'smart_{n}_raw' for n in n_columns]

In [6]:
df = pd.DataFrame()
for file in csv_files:
    print(file)
    df_aux = pd.read_csv(f'../data/data_q3_2024/{file}')
    id_cols = [c for c in df_aux.columns[:11]]
    cols = id_cols + normalized_cols
    df_aux = df_aux[df_aux['model'].isin(['ST16000NM001G', 'ST12000NM0008'])][cols]
    df = pd.concat([df, df_aux])

print(df.shape)
df.head()

2024-07-01.csv
2024-07-02.csv
2024-07-03.csv
2024-07-04.csv
2024-07-05.csv
2024-07-06.csv
2024-07-07.csv
2024-07-08.csv
2024-07-09.csv
2024-07-10.csv
2024-07-11.csv
2024-07-12.csv
2024-07-13.csv
2024-07-14.csv
2024-07-15.csv
2024-07-16.csv
2024-07-17.csv
2024-07-18.csv
2024-07-19.csv
2024-07-20.csv
2024-07-21.csv
2024-07-22.csv
2024-07-23.csv
2024-07-24.csv
2024-07-25.csv
2024-07-26.csv
2024-07-27.csv
2024-07-28.csv

C:\Users\USER\AppData\Local\Temp\ipykernel_17676\3225125251.py:4: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_aux = pd.read_csv(f'../data/data_q3_2024/{file}')

2024-07-29.csv

C:\Users\USER\AppData\Local\Temp\ipykernel_17676\3225125251.py:4: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_aux = pd.read_csv(f'../data/data_q3_2024/{file}')

2024-07-30.csv

C:\Users\USER\AppData\Local\Temp\ipykernel_17676\3225125251.py:4: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_aux = pd.read_csv(f'../data/data_q3_2024/{file}')

2024-07-31.csv

C:\Users\USER\AppData\Local\Temp\ipykernel_17676\3225125251.py:4: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_aux = pd.read_csv(f'../data/data_q3_2024/{file}')

(1634170, 26)

,date,serial_number,model,capacity_bytes,failure,datacenter,cluster_id,vault_id,pod_id,pod_slot_num,is_legacy_format,smart_1_normalized,smart_5_normalized,smart_7_normalized,smart_184_normalized,smart_187_normalized,smart_188_normalized,smart_189_normalized,smart_190_normalized,smart_193_normalized,smart_194_normalized,smart_197_normalized,smart_198_normalized,smart_240_normalized,smart_241_normalized,smart_242_normalized
45,2024-07-01,ZL27FLBV,ST16000NM001G,16000900661248,0,sac0,0,1021,0,32.0,False,81.0,100.0,83.0,NaN,100.0,100.0,NaN,74.0,100.0,26.0,100.0,100.0,100.0,100.0,100.0
137,2024-07-01,ZL2N22P0,ST16000NM001G,16000900661248,0,sac0,0,1021,2,24.0,False,80.0,100.0,73.0,NaN,100.0,100.0,NaN,61.0,100.0,39.0,100.0,100.0,100.0,100.0,100.0
180,2024-07-01,ZL2MM1KZ,ST16000NM001G,16000900661248,0,sac0,0,1021,3,23.0,False,84.0,100.0,88.0,NaN,100.0,100.0,NaN,70.0,100.0,30.0,100.0,100.0,100.0,100.0,100.0
181,2024-07-01,ZL2NQPLJ,ST16000NM001G,16000900661248,0,sac0,0,1021,3,18.0,False,83.0,100.0,89.0,NaN,100.0,100.0,NaN,71.0,100.0,29.0,100.0,100.0,100.0,100.0,100.0
182,2024-07-01,ZL2NRJCR,ST16000NM001G,16000900661248,0,sac0,0,1021,3,20.0,False,79.0,100.0,89.0,NaN,100.0,100.0,NaN,70.0,100.0,30.0,100.0,100.0,100.0,100.0,100.0

In [7]:
df.to_csv('../data/processed/jul_2024.csv', index=False)